source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

pod 'SWRevealViewController', '~> 2.1.0'
pod 'SMCalloutView'
pod 'ActionSheetPicker-3.0'
pod 'FDTake'
pod 'SORelativeDateTransformer', '~> 1.1.10'
pod 'RestKit'

target :icreatedTests do
  pod 'OCMock'
  pod 'Specta'
  pod 'Expecta'
  pod 'RestKit/Testing'
end

xcodeproj 'icreated.xcodeproj'